plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
  cpu:
    - 'current'
    - 'x64'
    - 'arm64'
  libc:
    - 'current'
    - 'glibc'
    - 'musl'
